WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600

FIELD_WIDTH = WINDOW_WIDTH * 0.45
BORDER_WIDTH = FIELD_WIDTH * 0.05
TRIANGLES_HEIGHT = (WINDOW_HEIGHT - 2 * BORDER_WIDTH) * 0.4
TRIANGLES_BASE_LENGTH = (FIELD_WIDTH * 2 - 4 * BORDER_WIDTH) / 12

DICE_LENGTH = WINDOW_WIDTH / 16
DICE_POSITION = (FIELD_WIDTH * 1.5 + BORDER_WIDTH * 3, WINDOW_HEIGHT / 2 - DICE_LENGTH / 2)
